// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package post

import (
	"github.com/nuxtblog/nuxtblog/api/post"
)

type ControllerV1 struct{}

func NewV1() post.IPostV1 {
	return &ControllerV1{}
}
