// Code generated by GoFrame CLI tool. DO NOT EDIT.

package nav_menu

import (
	"context"

	v1 "github.com/nuxtblog/nuxtblog/api/nav_menu/v1"
)

type INavMenuV1 interface {
	NavMenuList(ctx context.Context, req *v1.NavMenuListReq) (res *v1.NavMenuListRes, err error)
	NavMenuCreate(ctx context.Context, req *v1.NavMenuCreateReq) (res *v1.NavMenuCreateRes, err error)
	NavMenuGetOne(ctx context.Context, req *v1.NavMenuGetOneReq) (res *v1.NavMenuGetOneRes, err error)
	NavMenuUpdate(ctx context.Context, req *v1.NavMenuUpdateReq) (res *v1.NavMenuUpdateRes, err error)
	NavMenuDelete(ctx context.Context, req *v1.NavMenuDeleteReq) (res *v1.NavMenuDeleteRes, err error)
	NavMenuByLocation(ctx context.Context, req *v1.NavMenuByLocationReq) (res *v1.NavMenuByLocationRes, err error)
}
