// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

// conversationsDao is the data access object for the table conversations.
// You can define custom methods on it to extend its functionality as needed.
type conversationsDao struct {
	*internal.ConversationsDao
}

var (
	// Conversations is a globally accessible object for table conversations operations.
	Conversations = conversationsDao{internal.NewConversationsDao()}
)
