// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
	"github.com/nuxtblog/nuxtblog/internal/model/entity"
	"context"
)

type docCollectionsDao struct {
	*internal.DocCollectionsDao
}

var DocCollections = docCollectionsDao{internal.NewDocCollectionsDao()}

// Create inserts a new doc collection and returns its id.
func (d *docCollectionsDao) Create(ctx context.Context, col *entity.DocCollections) (id int64, err error) {
	return d.Ctx(ctx).FieldsEx("id").InsertAndGetId(col)
}

// GetBySlug returns a doc collection by its slug (excluding soft-deleted).
func (d *docCollectionsDao) GetBySlug(ctx context.Context, slug string) (col *entity.DocCollections, err error) {
	err = d.Ctx(ctx).Where("slug", slug).WhereNull("deleted_at").Scan(&col)
	return
}
