// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

type docStatsDao struct {
	*internal.DocStatsDao
}

var DocStats = docStatsDao{internal.NewDocStatsDao()}
