// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

type docRevisionsDao struct {
	*internal.DocRevisionsDao
}

var DocRevisions = docRevisionsDao{internal.NewDocRevisionsDao()}
