// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
	"github.com/nuxtblog/nuxtblog/internal/model/entity"
	"context"
)

type docsDao struct {
	*internal.DocsDao
}

var Docs = docsDao{internal.NewDocsDao()}

// Create inserts a new doc and returns its id.
func (d *docsDao) Create(ctx context.Context, doc *entity.Docs) (id int64, err error) {
	return d.Ctx(ctx).FieldsEx("id").InsertAndGetId(doc)
}

// GetById returns a doc by id (excluding soft-deleted).
func (d *docsDao) GetById(ctx context.Context, id int64) (doc *entity.Docs, err error) {
	err = d.Ctx(ctx).Where("id", id).WhereNull("deleted_at").Scan(&doc)
	return
}

// GetBySlug returns a doc by slug (excluding soft-deleted).
func (d *docsDao) GetBySlug(ctx context.Context, slug string) (doc *entity.Docs, err error) {
	err = d.Ctx(ctx).Where("slug", slug).WhereNull("deleted_at").Scan(&doc)
	return
}
