// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

// mediasDao is the data access object for the table medias.
// You can define custom methods on it to extend its functionality as needed.
type mediasDao struct {
	*internal.MediasDao
}

var (
	// Medias is a globally accessible object for table medias operations.
	Medias = mediasDao{internal.NewMediasDao()}
)

// Add your custom methods and functionality below.
