// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
	"github.com/nuxtblog/nuxtblog/internal/model/entity"
	"context"
)

type momentsDao struct {
	*internal.MomentsDao
}

var Moments = momentsDao{internal.NewMomentsDao()}

// Create inserts a new moment and returns its id.
func (d *momentsDao) Create(ctx context.Context, m *entity.Moments) (id int64, err error) {
	return d.Ctx(ctx).InsertAndGetId(m)
}

// GetById returns a moment by id (excluding soft-deleted).
func (d *momentsDao) GetById(ctx context.Context, id int64) (m *entity.Moments, err error) {
	err = d.Ctx(ctx).Where("id", id).WhereNull("deleted_at").Scan(&m)
	return
}
