// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

// objectTaxonomiesDao is the data access object for the table object_taxonomies.
// You can define custom methods on it to extend its functionality as needed.
type objectTaxonomiesDao struct {
	*internal.ObjectTaxonomiesDao
}

var (
	// ObjectTaxonomies is a globally accessible object for table object_taxonomies operations.
	ObjectTaxonomies = objectTaxonomiesDao{internal.NewObjectTaxonomiesDao()}
)

// Add your custom methods and functionality below.
