// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

// optionsDao is the data access object for the table options.
// You can define custom methods on it to extend its functionality as needed.
type optionsDao struct {
	*internal.OptionsDao
}

var (
	// Options is a globally accessible object for table options operations.
	Options = optionsDao{internal.NewOptionsDao()}
)

// Add your custom methods and functionality below.
