// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
	"github.com/nuxtblog/nuxtblog/internal/model/entity"
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

type postsDao struct {
	*internal.PostsDao
}

var Posts = postsDao{internal.NewPostsDao()}

// ----------------------------------------------------------------
//  Create
// ----------------------------------------------------------------

func (d *postsDao) Create(ctx context.Context, post *entity.Posts) (id int64, err error) {
	return d.Ctx(ctx).FieldsEx("id").InsertAndGetId(post)
}

// ----------------------------------------------------------------
//  Delete
// ----------------------------------------------------------------

// DeleteById permanently removes a post by setting deleted_at (soft delete).
// GoFrame automatically converts Delete() to UPDATE SET deleted_at=NOW().
func (d *postsDao) DeleteById(ctx context.Context, id int64) error {
	_, err := g.DB().Ctx(ctx).Model("posts").Where("id", id).Delete()
	return err
}

// TrashById moves a post to the trash by setting status=5.
func (d *postsDao) TrashById(ctx context.Context, id int64) error {
	_, err := g.DB().Ctx(ctx).Model("posts").Where("id", id).Data(g.Map{"status": 5}).Update()
	return err
}

// RestoreById recovers a trashed post, resetting status to draft.
func (d *postsDao) RestoreById(ctx context.Context, id int64) error {
	_, err := g.DB().Ctx(ctx).Model("posts").Where("id", id).Where("status", 5).Data(g.Map{"status": 1}).Update()
	return err
}

// ----------------------------------------------------------------
//  Update
// ----------------------------------------------------------------

// UpdateById 只更新非零值字段，传什么改什么
func (d *postsDao) UpdateById(ctx context.Context, id int64, data interface{}) error {
	_, err := d.Ctx(ctx).Where("id", id).Data(data).Update()
	return err
}

// ----------------------------------------------------------------
//  Query
// ----------------------------------------------------------------

func (d *postsDao) GetById(ctx context.Context, id int64) (post *entity.Posts, err error) {
	err = d.Ctx(ctx).Where("id", id).Scan(&post)
	return
}

func (d *postsDao) GetBySlug(ctx context.Context, slug string) (post *entity.Posts, err error) {
	err = d.Ctx(ctx).Where("slug", slug).Scan(&post)
	return
}

// GetList 分页列表
func (d *postsDao) GetList(ctx context.Context, page, size int, where ...interface{}) (list []*entity.Posts, total int, err error) {
	m := d.Ctx(ctx)
	if len(where) > 0 {
		m = m.Where(where[0], where[1:]...)
	}
	total, err = m.Count()
	if err != nil || total == 0 {
		return
	}
	err = m.Page(page, size).OrderDesc("created_at").Scan(&list)
	return
}

// ----------------------------------------------------------------
//  常用条件封装
// ----------------------------------------------------------------

// Published 只查已发布的文章
func (d *postsDao) Published(ctx context.Context) *gdb.Model {
	return d.Ctx(ctx).Where("status", 2).WhereNull("deleted_at")
}

// ByAuthor 按作者过滤
func (d *postsDao) ByAuthor(ctx context.Context, authorId int64) *gdb.Model {
	return d.Ctx(ctx).Where("author_id", authorId).WhereNull("deleted_at")
}
