// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

// postStatsDao is the data access object for the table post_stats.
// You can define custom methods on it to extend its functionality as needed.
type postStatsDao struct {
	*internal.PostStatsDao
}

var (
	// PostStats is a globally accessible object for table post_stats operations.
	PostStats = postStatsDao{internal.NewPostStatsDao()}
)

// Add your custom methods and functionality below.
