// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

// postSeoDao is the data access object for the table post_seo.
// You can define custom methods on it to extend its functionality as needed.
type postSeoDao struct {
	*internal.PostSeoDao
}

var (
	// PostSeo is a globally accessible object for table post_seo operations.
	PostSeo = postSeoDao{internal.NewPostSeoDao()}
)

// Add your custom methods and functionality below.
