// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

// postRevisionsDao is the data access object for the table post_revisions.
// You can define custom methods on it to extend its functionality as needed.
type postRevisionsDao struct {
	*internal.PostRevisionsDao
}

var (
	// PostRevisions is a globally accessible object for table post_revisions operations.
	PostRevisions = postRevisionsDao{internal.NewPostRevisionsDao()}
)

// Add your custom methods and functionality below.
