// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

// postMetasDao is the data access object for the table post_metas.
// You can define custom methods on it to extend its functionality as needed.
type postMetasDao struct {
	*internal.PostMetasDao
}

var (
	// PostMetas is a globally accessible object for table post_metas operations.
	PostMetas = postMetasDao{internal.NewPostMetasDao()}
)

// Add your custom methods and functionality below.
