// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

// reportsDao is the data access object for the table reports.
// You can define custom methods on it to extend its functionality as needed.
type reportsDao struct {
	*internal.ReportsDao
}

var (
	// Reports is a globally accessible object for table reports operations.
	Reports = reportsDao{internal.NewReportsDao()}
)
