// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

// taxonomiesDao is the data access object for the table taxonomies.
// You can define custom methods on it to extend its functionality as needed.
type taxonomiesDao struct {
	*internal.TaxonomiesDao
}

var (
	// Taxonomies is a globally accessible object for table taxonomies operations.
	Taxonomies = taxonomiesDao{internal.NewTaxonomiesDao()}
)

// Add your custom methods and functionality below.
