// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

// termsDao is the data access object for the table terms.
// You can define custom methods on it to extend its functionality as needed.
type termsDao struct {
	*internal.TermsDao
}

var (
	// Terms is a globally accessible object for table terms operations.
	Terms = termsDao{internal.NewTermsDao()}
)

// Add your custom methods and functionality below.
