// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
	"github.com/nuxtblog/nuxtblog/internal/util/idgen"
	"context"
)

// userActionsDao is the data access object for the table user_actions.
// You can define custom methods on it to extend its functionality as needed.
type userActionsDao struct {
	*internal.UserActionsDao
}

var (
	// UserActions is a globally accessible object for table user_actions operations.
	UserActions = userActionsDao{internal.NewUserActionsDao()}
)

// InsertAction inserts a new user action record and returns the new ID.
func (d *userActionsDao) InsertAction(ctx context.Context, userID int64, action, objectType string, objectID int64, extra string) (int64, error) {
	cols := d.Columns()
	result, err := d.Ctx(ctx).Data(map[string]any{
		cols.Id:         idgen.New(),
		cols.UserId:     userID,
		cols.Action:     action,
		cols.ObjectType: objectType,
		cols.ObjectId:   objectID,
		cols.Extra:      extra,
	}).Insert()
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

