// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

// userBookmarksDao is the data access object for the table user_bookmarks.
// You can define custom methods on it to extend its functionality as needed.
type userBookmarksDao struct {
	*internal.UserBookmarksDao
}

var (
	// UserBookmarks is a globally accessible object for table user_bookmarks operations.
	UserBookmarks = userBookmarksDao{internal.NewUserBookmarksDao()}
)

// Add your custom methods and functionality below.
