// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
	"context"
	"strings"
)

// userProfilesDao is the data access object for the table user_profiles.
// You can define custom methods on it to extend its functionality as needed.
type userProfilesDao struct {
	*internal.UserProfilesDao
}

var (
	// UserProfiles is a globally accessible object for table user_profiles operations.
	UserProfiles = userProfilesDao{internal.NewUserProfilesDao()}
)

// GetCheckinCache returns the cached streak and last check-in date for a user.
func (d *userProfilesDao) GetCheckinCache(ctx context.Context, userID int64) (streak int, lastDate string, err error) {
	cols := d.Columns()
	type Row struct {
		CheckinStreak   int    `orm:"checkin_streak"`
		LastCheckinDate string `orm:"last_checkin_date"`
	}
	var row Row
	err = d.Ctx(ctx).
		Fields(cols.CheckinStreak, cols.LastCheckinDate).
		Where(cols.UserId, userID).
		Scan(&row)
	if err != nil && strings.Contains(err.Error(), "no rows") {
		err = nil
	}
	return row.CheckinStreak, row.LastCheckinDate, err
}

// UpdateCheckinStreak upserts checkin_streak and last_checkin_date for a user.
// Uses UPDATE-then-INSERT to stay compatible with all GoFrame drivers.
func (d *userProfilesDao) UpdateCheckinStreak(ctx context.Context, userID int64, streak int, date string) error {
	cols := d.Columns()
	result, err := d.Ctx(ctx).
		Data(map[string]any{
			cols.CheckinStreak:   streak,
			cols.LastCheckinDate: date,
		}).
		Where(cols.UserId, userID).
		Update()
	if err != nil {
		return err
	}
	affected, _ := result.RowsAffected()
	if affected > 0 {
		return nil
	}
	// No existing row — insert one.
	_, err = d.Ctx(ctx).
		Data(map[string]any{
			cols.UserId:          userID,
			cols.CheckinStreak:   streak,
			cols.LastCheckinDate: date,
		}).
		Insert()
	return err
}
