// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"

	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
	"github.com/nuxtblog/nuxtblog/internal/model/entity"
)

// usersDao is the data access object for the table users.
// You can define custom methods on it to extend its functionality as needed.
type usersDao struct {
	*internal.UsersDao
}

var (
	// Users is a globally accessible object for table users operations.
	Users = usersDao{internal.NewUsersDao()}
)

func (d *usersDao) GetById(ctx context.Context, id int64) (user *entity.Users, err error) {
	err = d.Ctx(ctx).Where("id", id).WhereNull("deleted_at").Scan(&user)
	return
}

func (d *usersDao) GetList(ctx context.Context, page, size int, where ...interface{}) (list []*entity.Users, total int, err error) {
	m := d.Ctx(ctx).WhereNull("deleted_at")
	if len(where) > 0 {
		m = m.Where(where[0], where[1:]...)
	}
	total, err = m.Count()
	if err != nil || total == 0 {
		return
	}
	err = m.Page(page, size).OrderDesc("created_at").Scan(&list)
	return
}
