// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

// userTokensDao is the data access object for the table user_tokens.
// You can define custom methods on it to extend its functionality as needed.
type userTokensDao struct {
	*internal.UserTokensDao
}

var (
	// UserTokens is a globally accessible object for table user_tokens operations.
	UserTokens = userTokensDao{internal.NewUserTokensDao()}
)
