// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

// userLikesDao is the data access object for the table user_likes.
// You can define custom methods on it to extend its functionality as needed.
type userLikesDao struct {
	*internal.UserLikesDao
}

var (
	// UserLikes is a globally accessible object for table user_likes operations.
	UserLikes = userLikesDao{internal.NewUserLikesDao()}
)

// Add your custom methods and functionality below.
