// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

// userFollowsDao is the data access object for the table user_follows.
// You can define custom methods on it to extend its functionality as needed.
type userFollowsDao struct {
	*internal.UserFollowsDao
}

var (
	// UserFollows is a globally accessible object for table user_follows operations.
	UserFollows = userFollowsDao{internal.NewUserFollowsDao()}
)
