// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

// userProfilesDao is the data access object for the table user_profiles.
// You can define custom methods on it to extend its functionality as needed.
type userProfilesDao struct {
	*internal.UserProfilesDao
}

var (
	// UserProfiles is a globally accessible object for table user_profiles operations.
	UserProfiles = userProfilesDao{internal.NewUserProfilesDao()}
)
