// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/nuxtblog/nuxtblog/internal/dao/internal"
)

// userOauthDao is the data access object for the table user_oauth.
// You can define custom methods on it to extend its functionality as needed.
type userOauthDao struct {
	*internal.UserOauthDao
}

var (
	// UserOauth is a globally accessible object for table user_oauth operations.
	UserOauth = userOauthDao{internal.NewUserOauthDao()}
)
