// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package option

import (
	"github.com/nuxtblog/nuxtblog/api/option"
)

type ControllerV1 struct{}

func NewV1() option.IOptionV1 {
	return &ControllerV1{}
}
