// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package taxonomy

import (
	"github.com/nuxtblog/nuxtblog/api/taxonomy"
)

type ControllerV1 struct{}

func NewV1() taxonomy.ITaxonomyV1 {
	return &ControllerV1{}
}
